ALTER TABLE entreprises
    ADD COLUMN IF NOT EXISTS adresse TEXT,
    ADD COLUMN IF NOT EXISTS telephone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS site_web VARCHAR(255),
    ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS devise VARCHAR(10) NOT NULL DEFAULT 'XOF',
    ADD COLUMN IF NOT EXISTS taux_tva_defaut NUMERIC(5,2) NOT NULL DEFAULT 18.00,
    ADD COLUMN IF NOT EXISTS debut_exercice_mois INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
